#!/usr/bin/env ruby

git_bundles = [ 
  # "git://github.com/ervandew/supertab.git",
  # "git://github.com/godlygeek/tabular.git",
  # "git://github.com/msanders/snipmate.vim.git",
  # "git://github.com/pangloss/vim-javascript.git",
  # "git://github.com/scrooloose/nerdtree.git",
  # "git://github.com/timcharper/textile.vim.git",
  # "git://github.com/tpope/vim-git.git",
  # "git://github.com/tpope/vim-repeat.git",
  # "git://github.com/tsaleh/vim-matchit.git",
  # "git://github.com/tsaleh/vim-shoulda.git",
  # "git://github.com/tsaleh/vim-tcomment.git",
  # "git://github.com/tsaleh/vim-tmux.git",
  # "git://github.com/jgdavey/tslime.vim.git",
  # "git://github.com/jgdavey/vim-turbux.git",
  # "git://github.com/tpope/vim-surround.git",
  # "git://github.com/Lokaltog/vim-powerline.git",
  # "git://github.com/wincent/Command-T.git",
  # "git://github.com/kana/vim-smartinput.git",

  "git://github.com/tpope/vim-fugitive.git",
  "git://github.com/tpope/vim-haml.git",
  "git://github.com/tpope/vim-markdown.git",
  "git://github.com/tpope/vim-rails.git",
  "git://github.com/tpope/vim-vividchalk.git",
  "git://github.com/vim-ruby/vim-ruby.git",
  "git://github.com/rphillips/vim-zoomwin.git",
  "git://github.com/skwp/vim-powerline.git::develop",
  "git://github.com/tpope/vim-commentary.git",
  "git://github.com/altercation/vim-colors-solarized.git",
  "git://github.com/kchmck/vim-coffee-script.git",
  "git://github.com/russ/rtf-highlight.git",
  "git://github.com/mattn/webapi-vim.git",
  "git://github.com/mattn/gist-vim.git::use_api",
  "git://github.com/tpope/vim-endwise.git",
  "git://github.com/digitaltoad/vim-jade.git",
  "git://github.com/rosstimson/scala-vim-support.git",
  "git://github.com/groenewege/vim-less.git"
]

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.cd(bundles_dir)

puts "trashing everything (lookout!)"
Dir["*"].each {|d| FileUtils.rm_rf d }

git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '').sub(/::.*/, '')
  puts "unpacking #{url} into #{dir}"
  if url.include?('::')
    url, branch = url.split('::')
    `git clone #{url} #{dir}`
    `cd #{dir} && git checkout #{branch}`
  else
    `git clone #{url} #{dir}`
  end
  FileUtils.rm_rf(File.join(dir, ".git"))
end

# `cd #{File.expand_path(File.join(bundles_dir.gsub(/bundle$/, ""), "Command-T"))} && rake make`
